name: US4 - Documentation automatique backend

on:
  push:
    branches: [ "main", "Artfact" ]

jobs:
  doc:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installation des dépendances
        run: |
          pip install sphinx sphinx-rtd-theme

      - name: Génération de la documentation
        run: |
          cd docs
          make html

      - name: Publication de la documentation en artefact
        uses: actions/upload-artifact@v4
        with:
          name: documentation-backend
          path: docs/build/html/
